### ISSUE TITLE
Getting started walkthrough is incorrect for Windows

### ISSUE THREAD

**Issue by jbrinkman** [auth0/extend#48]
The walkthrough in the getting started includes directions to use the following command `DEBUG=zerocrm npm start` which does not work on Windows.

## Repro steps
1. On Windows, attempt to follow the walkthrough exactly as shown

## Expected
1. The walkthrough runs with no errors

## Actual
1. An error is displayed: 'DEBUG' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cfjedimaster** [comment]
This looks like it was already deployed (the fix I mean).
