### ISSUE TITLE
npm start script references non-existent proxy.js file

### ISSUE THREAD

**Issue by shakeelmohamed** [auth0/extend#5]
In the root `package.json` the `npm start` script is configured to run `node proxy.js`, but that file does not exist in the repo 😄

**Comment by duboff** [comment]
@shakeelmohamed Have you figured out a way around this?

**Comment by kristyoverton** [comment]
Make sure you're working in the samples/zerocrm directory. You'll need to run npm install for that directory and create your .env file there too.
